apiVersion: v1
kind: Service
metadata:
  name: osint-fastapi-backend
  namespace: osint-platform
spec:
  selector:
    app: osint-backend
  ports:
    - name: http
      port: 8000
      targetPort: 5000
  type: ClusterIP