# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osint-backend
  namespace: osint-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osint-backend
  template:
    metadata:
      labels:
        app: osint-backend
    spec:
      containers:
      - name: backend
        image: osint-platform/backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: osint-backend
  namespace: osint-platform
spec:
  selector:
    app: osint-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osint-frontend
  namespace: osint-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osint-frontend
  template:
    metadata:
      labels:
        app: osint-frontend
    spec:
      containers:
      - name: frontend
        image: osint-platform/frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: osint-frontend
  namespace: osint-platform
spec:
  selector:
    app: osint-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
# MCP Social Media Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-social-media
  namespace: osint-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-social-media
  template:
    metadata:
      labels:
        app: mcp-social-media
    spec:
      containers:
      - name: mcp-server
        image: osint-platform/mcp-social-media:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8010
        env:
        - name: MCP_SERVER_PORT
          value: "8010"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-social-media
  namespace: osint-platform
spec:
  selector:
    app: mcp-social-media
  ports:
  - port: 8010
    targetPort: 8010
  type: ClusterIP
---
# MCP Infrastructure Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-infrastructure
  namespace: osint-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-infrastructure
  template:
    metadata:
      labels:
        app: mcp-infrastructure
    spec:
      containers:
      - name: mcp-server
        image: osint-platform/mcp-infrastructure:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8020
        env:
        - name: MCP_SERVER_PORT
          value: "8020"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-infrastructure
  namespace: osint-platform
spec:
  selector:
    app: mcp-infrastructure
  ports:
  - port: 8020
    targetPort: 8020
  type: ClusterIP
---
# MCP Threat Intel Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-threat-intel
  namespace: osint-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-threat-intel
  template:
    metadata:
      labels:
        app: mcp-threat-intel
    spec:
      containers:
      - name: mcp-server
        image: osint-platform/mcp-threat-intel:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8030
        env:
        - name: MCP_SERVER_PORT
          value: "8030"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-threat-intel
  namespace: osint-platform
spec:
  selector:
    app: mcp-threat-intel
  ports:
  - port: 8030
    targetPort: 8030
  type: ClusterIP