apiVersion: v1
kind: Namespace
metadata:
  name: osint-platform
  labels:
    name: osint-platform
    purpose: enterprise-osint
    security: restricted
  annotations:
    description: "Enterprise OSINT Platform with Vault and PostgreSQL"