apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osint-reports-pvc
  namespace: osint-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath