apiVersion: apps/v1
kind: Deployment
metadata:
  name: osint-simple-frontend
  namespace: osint-platform
  labels:
    app: osint-simple-frontend
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osint-simple-frontend
  template:
    metadata:
      labels:
        app: osint-simple-frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: osint-platform/simple-frontend:v2.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: BACKEND_URL
          value: "http://osint-fastapi-backend:8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: osint-simple-frontend
  namespace: osint-platform
spec:
  selector:
    app: osint-simple-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer