# Default values for osint-platform
# Enterprise OSINT Platform Helm Chart - Current Architecture
replicaCount:
  frontend: 2
  backend: 2
  mcpInfrastructureEnhanced: 2
  mcpThreatEnhanced: 1
  mcpTechnicalEnhanced: 1
  mcpSocialEnhanced: 1
  mcpFinancialEnhanced: 1

image:
  registry: ""
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# Frontend configuration (React SPA)
frontend:
  image:
    repository: osint-platform/simple-frontend
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# Backend configuration (Flask REST API)
backend:
  image:
    repository: osint-platform/simple-backend
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    FLASK_ENV: production
    LOG_LEVEL: INFO
    POSTGRES_URL: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/osint_audit"

# Enhanced MCP Servers configuration (Current Architecture)
mcp:
  # Infrastructure Advanced MCP Server (FastAPI)
  infrastructureEnhanced:
    image:
      repository: osint-platform/infrastructure-advanced
    port: 8021
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    capabilities:
      - certificate_transparency
      - passive_dns
      - asn_lookup
      - reverse_ip
      - port_scan
      - web_technologies
  
  # Threat Intelligence Aggregator (FastAPI)
  threatEnhanced:
    image:
      repository: osint-platform/threat-aggregator
    port: 8020
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    capabilities:
      - threat_check_ip
      - threat_check_domain
      - threat_check_hash
      - threat_hunt
  
  # AI-Powered Analyzer (FastAPI)
  technicalEnhanced:
    image:
      repository: osint-platform/ai-analyzer
    port: 8050
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
    capabilities:
      - ai_generate_executive_summary
      - ai_threat_assessment
      - ai_risk_analysis
  
  # Social Media Enhanced (Flask)
  socialEnhanced:
    image:
      repository: osint-platform/social-media-enhanced
    port: 8010
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    capabilities:
      - social_twitter_profile
      - social_linkedin_company
      - social_reddit_search
  
  # Financial Enhanced (Flask)
  financialEnhanced:
    image:
      repository: osint-platform/financial-enhanced
    port: 8040
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    capabilities:
      - financial_sec_filings
      - financial_company_analysis

# PostgreSQL configuration (Audit Database)
postgresql:
  enabled: true
  auth:
    username: postgres
    password: "changeme-secure-password"
    database: osint_audit
  primary:
    persistence:
      enabled: true
      size: 50Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  metrics:
    enabled: true
  audit:
    enabled: true
    logConnections: true
    logDisconnections: true

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: true
    password: "changeme"
  master:
    persistence:
      enabled: true
      size: 8Gi
  metrics:
    enabled: true

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  hosts:
    - host: osint.example.com
      paths:
        - path: /
          pathType: Prefix
          backend: frontend
        - path: /api
          pathType: Prefix
          backend: backend
        - path: /socket.io
          pathType: Prefix
          backend: backend
  tls:
    - secretName: osint-tls
      hosts:
        - osint.example.com

# Storage configuration
persistence:
  reports:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteMany
    size: 100Gi

# Security configuration
security:
  secretKey: "changeme-to-random-string"
  jwtSecretKey: "changeme-to-random-jwt-secret"

# API Keys - MUST be provided via External Secrets in production
apiKeys:
  # External Secrets configuration (recommended)
  externalSecrets:
    enabled: true
    secretStore: vault-backend
    refreshInterval: 5m
  
  # AI Enhancement APIs
  openai: ""
  
  # Threat Intelligence APIs
  virustotal: ""
  abuseipdb: ""
  shodan: ""
  alienvault: ""
  
  # Social Media APIs
  twitterBearer: ""
  redditClientId: ""
  redditClientSecret: ""
  
  # Financial APIs
  alphaVantage: ""
  secApi: ""

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

# Auto-scaling
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node affinity
nodeSelector: {}
tolerations: []
affinity: {}