apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: osint-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osint-postgres
  namespace: osint-platform
spec:
  serviceName: osint-postgres
  replicas: 1
  selector:
    matchLabels:
      app: osint-postgres
  template:
    metadata:
      labels:
        app: osint-postgres
        component: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: osint_db
        - name: POSTGRES_USER
          value: osint_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osint-secrets
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - osint_user
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - osint_user
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: osint-postgres
  namespace: osint-platform
spec:
  selector:
    app: osint-postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP