{{- if .Values.apiKeys.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "osint-platform.fullname" . }}-api-keys
  labels:
    {{- include "osint-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.apiKeys.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.apiKeys.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "osint-platform.fullname" . }}-api-keys
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        openai-api-key: "{{ `{{ .openai_api_key }}` }}"
        virustotal-api-key: "{{ `{{ .virustotal_api_key }}` }}"
        abuseipdb-api-key: "{{ `{{ .abuseipdb_api_key }}` }}"
        shodan-api-key: "{{ `{{ .shodan_api_key }}` }}"
        twitter-bearer-token: "{{ `{{ .twitter_bearer_token }}` }}"
        reddit-client-id: "{{ `{{ .reddit_client_id }}` }}"
        reddit-client-secret: "{{ `{{ .reddit_client_secret }}` }}"
        alpha-vantage-api-key: "{{ `{{ .alpha_vantage_api_key }}` }}"
  data:
    - secretKey: openai_api_key
      remoteRef:
        key: api-keys
        property: openai_api_key
    - secretKey: virustotal_api_key
      remoteRef:
        key: api-keys
        property: virustotal_api_key
    - secretKey: abuseipdb_api_key
      remoteRef:
        key: api-keys
        property: abuseipdb_api_key
    - secretKey: shodan_api_key
      remoteRef:
        key: api-keys
        property: shodan_api_key
    - secretKey: twitter_bearer_token
      remoteRef:
        key: api-keys
        property: twitter_bearer_token
    - secretKey: reddit_client_id
      remoteRef:
        key: api-keys
        property: reddit_client_id
    - secretKey: reddit_client_secret
      remoteRef:
        key: api-keys
        property: reddit_client_secret
    - secretKey: alpha_vantage_api_key
      remoteRef:
        key: api-keys
        property: alpha_vantage_api_key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "osint-platform.fullname" . }}-secrets
  labels:
    {{- include "osint-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.apiKeys.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "osint-platform.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        jwt-secret-key: "{{ `{{ .jwt_secret_key }}` }}"
        secret-key: "{{ `{{ .secret_key }}` }}"
  data:
    - secretKey: jwt_secret_key
      remoteRef:
        key: app-config
        property: jwt_secret_key
    - secretKey: secret_key
      remoteRef:
        key: app-config
        property: secret_key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "osint-platform.fullname" . }}-postgresql
  labels:
    {{- include "osint-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ .Values.apiKeys.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "osint-platform.fullname" . }}-postgresql
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        postgres-password: "{{ `{{ .postgres_password }}` }}"
        postgres-user: "{{ `{{ .postgres_user }}` }}"
  data:
    - secretKey: postgres_password
      remoteRef:
        key: database-config
        property: postgres_password
    - secretKey: postgres_user
      remoteRef:
        key: database-config
        property: postgres_user
{{- end }}